version:"3.3"

services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime
    - /etc/motioneye:/etc/motioneye
    - /var/lib/motioneye:/var/lib/motioneye
    ports:
    - 8765:8765
    - 18081:8081

  domoticz:
    container_name: domoticz
    image: domoticz:domoticz
    restart: unless-stopped
    volumes:
    - /home/rod/domoticz/userdata:/opt/domoticz/userdata
    ports:
    - 8080:8080

